Namespace <- R6::R6Class(
  "pkg_DESCRIPTION",
  public = list(
    initialize = function(data) {
      private$data <- data
      self$.private <- private
    },
    print = function(...) {
      tmp <- tempfile()
      on.exit(file.remove(tmp))
      writeLines(private$data, con = tmp)
      writeLines(readLines(tmp))
    },
    .private = NULL,
    edit = function() {
      flat_file_edit(self, private)
    }
  ),
  private = list(
    data = NULL
  )
)

fetch_namespace <- function(path = "NAMESPACE") {
  if (!file.exists(path)) return(default_namespace())
  # TODO: add cleanup already started in namespace.R
  readLines(path)
}

default_namespace <- function() {
  # FIXME: class and printing
  c("# Generated by roxygen2: do not edit by hand", "")
}
